

import blog_comments_tag from './blog_comments.js';
import blog_social_sharing_tag from './blog_social_sharing.js';
import blog_subscribe_tag from './blog_subscribe.js';
import boolean_tag from './boolean.js';
import choice_tag from './choice.js';
import color_tag from './color.js';
import content_attribute_tag from './content_attribute.js';
import cta_tag from './cta.js';
import custom_widget_tag from './custom_widget.js';
import cycle_tag from './cycle.js';
import dnd_area_tag from './dnd_area.js';
import dnd_column_tag from './dnd_column.js';
import dnd_module_tag from './dnd_module.js';
import dnd_row_tag from './dnd_row.js';
import dnd_section_tag from './dnd_section.js';
import do_tag from './do.js';
import email_each_tag from './email_each.js';
import email_flex_area_tag from './email_flex_area.js';
import email_simple_subscription_tag from './email_simple_subscription.js';
import email_subscriptions_confirmation_tag from './email_subscriptions_confirmation.js';
import email_subscriptions_tag from './email_subscriptions.js';
import flip_tag from './flip.js';
import form_tag from './form.js';
import gallery_tag from './gallery.js';
import global_module_tag from './global_module.js';
import global_widget_tag from './global_widget.js';
import google_search_tag from './google_search.js';
import header_tag from './header.js';
import icon_tag from './icon.js';
import image_slider_tag from './image_slider.js';
import image_src_tag from './image_src.js';
import image_tag from './image.js';
import include_dnd_partial_tag from './include_dnd_partial.js';
import inline_rich_text_tag from './inline_rich_text.js';
import inline_text_tag from './inline_text.js';
import language_switcher_tag from './language_switcher.js';
import linked_image_tag from './linked_image.js';
import logo_tag from './logo.js';
import member_login_tag from './member_login.js';
import member_register_tag from './member_register.js';
import menu_tag from './menu.js';
import module_attribute_tag from './module_attribute.js';
import module_tag from './module.js';
import page_footer_tag from './page_footer.js';
import password_prompt_tag from './password_prompt.js';
import password_reset_request_tag from './password_reset_request.js';
import password_reset_tag from './password_reset.js';
import post_filter_tag from './post_filter.js';
import post_listing_tag from './post_listing.js';
import print_tag from './print.js';
import raw_html_tag from './raw_html.js';
import related_blog_posts_tag from './related_blog_posts.js';
import require_css_tag from './require_css.js';
import require_head_tag from './require_head.js';
import require_js_tag from './require_js.js';
import rich_text_tag from './rich_text.js';
import rss_listing_tag from './rss_listing.js';
import section_header_tag from './section_header.js';
import simple_menu_tag from './simple_menu.js';
import social_sharing_tag from './social_sharing.js';
import space_tag from './space.js';
import style_settings_tag from './style_settings.js';
import targeted_module_attribute_tag from './targeted_module_attribute.js';
import targeted_widget_attribute_tag from './targeted_widget_attribute.js';
import text_tag from './text.js';
import textarea_tag from './textarea.js';
import unless_tag from './unless.js';
import video_player_tag from './video_player.js';
import widget_attribute_tag from './widget_attribute.js';
import widget_block_tag from './widget_block.js';
import widget_container_tag from './widget_container.js';
import widget_wrapper_tag from './widget_wrapper.js';

export default function configure(env, config) {
  
  blog_comments_tag.register(env, config);
  blog_social_sharing_tag.register(env, config);
  blog_subscribe_tag.register(env, config);
  boolean_tag.register(env, config);
  choice_tag.register(env, config);
  color_tag.register(env, config);
  content_attribute_tag.register(env, config);
  cta_tag.register(env, config);
  custom_widget_tag.register(env, config);
  cycle_tag.register(env, config);
  dnd_area_tag.register(env, config);
  dnd_column_tag.register(env, config);
  dnd_module_tag.register(env, config);
  dnd_row_tag.register(env, config);
  dnd_section_tag.register(env, config);
  do_tag.register(env, config);
  email_each_tag.register(env, config);
  email_flex_area_tag.register(env, config);
  email_simple_subscription_tag.register(env, config);
  email_subscriptions_confirmation_tag.register(env, config);
  email_subscriptions_tag.register(env, config);
  flip_tag.register(env, config);
  form_tag.register(env, config);
  gallery_tag.register(env, config);
  global_module_tag.register(env, config);
  global_widget_tag.register(env, config);
  google_search_tag.register(env, config);
  header_tag.register(env, config);
  icon_tag.register(env, config);
  image_slider_tag.register(env, config);
  image_src_tag.register(env, config);
  image_tag.register(env, config);
  include_dnd_partial_tag.register(env, config);
  inline_rich_text_tag.register(env, config);
  inline_text_tag.register(env, config);
  language_switcher_tag.register(env, config);
  linked_image_tag.register(env, config);
  logo_tag.register(env, config);
  member_login_tag.register(env, config);
  member_register_tag.register(env, config);
  menu_tag.register(env, config);
  module_attribute_tag.register(env, config);
  module_tag.register(env, config);
  page_footer_tag.register(env, config);
  password_prompt_tag.register(env, config);
  password_reset_request_tag.register(env, config);
  password_reset_tag.register(env, config);
  post_filter_tag.register(env, config);
  post_listing_tag.register(env, config);
  print_tag.register(env, config);
  raw_html_tag.register(env, config);
  related_blog_posts_tag.register(env, config);
  require_css_tag.register(env, config);
  require_head_tag.register(env, config);
  require_js_tag.register(env, config);
  rich_text_tag.register(env, config);
  rss_listing_tag.register(env, config);
  section_header_tag.register(env, config);
  simple_menu_tag.register(env, config);
  social_sharing_tag.register(env, config);
  space_tag.register(env, config);
  style_settings_tag.register(env, config);
  targeted_module_attribute_tag.register(env, config);
  targeted_widget_attribute_tag.register(env, config);
  text_tag.register(env, config);
  textarea_tag.register(env, config);
  unless_tag.register(env, config);
  video_player_tag.register(env, config);
  widget_attribute_tag.register(env, config);
  widget_block_tag.register(env, config);
  widget_container_tag.register(env, config);
  widget_wrapper_tag.register(env, config);
};