

import blog_comments_init from './blog_comments.js';
import blog_social_sharing_init from './blog_social_sharing.js';
import blog_subscribe_init from './blog_subscribe.js';
import boolean_init from './boolean.js';
import choice_init from './choice.js';
import color_init from './color.js';
import cta_init from './cta.js';
import dnd_area_init from './dnd_area.js';
import dnd_column_init from './dnd_column.js';
import dnd_module_init from './dnd_module.js';
import dnd_row_init from './dnd_row.js';
import dnd_section_init from './dnd_section.js';
import email_simple_subscription_init from './email_simple_subscription.js';
import email_subscriptions_confirmation_init from './email_subscriptions_confirmation.js';
import email_subscriptions_init from './email_subscriptions.js';
import form_init from './form.js';
import gallery_init from './gallery.js';
import header_init from './header.js';
import image_src_init from './image_src.js';
import image_init from './image.js';
import include_dnd_partial_init from './include_dnd_partial.js';
import language_switcher_init from './language_switcher.js';
import linked_image_init from './linked_image.js';
import logo_init from './logo.js';
import menu_init from './menu.js';
import module_attribute_init from './module_attribute.js';
import module_init from './module.js';
import page_footer_init from './page_footer.js';
import password_prompt_init from './password_prompt.js';
import post_filter_init from './post_filter.js';
import post_listing_init from './post_listing.js';
import raw_html_init from './raw_html.js';
import related_blog_posts_init from './related_blog_posts.js';
import require_css_init from './require_css.js';
import require_head_init from './require_head.js';
import require_js_init from './require_js.js';
import rich_text_init from './rich_text.js';
import rss_listing_init from './rss_listing.js';
import section_header_init from './section_header.js';
import simple_menu_init from './simple_menu.js';
import social_sharing_init from './social_sharing.js';
import space_init from './space.js';
import text_init from './text.js';
import textarea_init from './textarea.js';
import video_player_init from './video_player.js';
import widget_attribute_init from './widget_attribute.js';
import widget_block_init from './widget_block.js';
import widget_container_init from './widget_container.js';

export default function configure(env, config) {
  
  blog_comments_init(env, config);
  blog_social_sharing_init(env, config);
  blog_subscribe_init(env, config);
  boolean_init(env, config);
  choice_init(env, config);
  color_init(env, config);
  cta_init(env, config);
  dnd_area_init(env, config);
  dnd_column_init(env, config);
  dnd_module_init(env, config);
  dnd_row_init(env, config);
  dnd_section_init(env, config);
  email_simple_subscription_init(env, config);
  email_subscriptions_confirmation_init(env, config);
  email_subscriptions_init(env, config);
  form_init(env, config);
  gallery_init(env, config);
  header_init(env, config);
  image_src_init(env, config);
  image_init(env, config);
  include_dnd_partial_init(env, config);
  language_switcher_init(env, config);
  linked_image_init(env, config);
  logo_init(env, config);
  menu_init(env, config);
  module_attribute_init(env, config);
  module_init(env, config);
  page_footer_init(env, config);
  password_prompt_init(env, config);
  post_filter_init(env, config);
  post_listing_init(env, config);
  raw_html_init(env, config);
  related_blog_posts_init(env, config);
  require_css_init(env, config);
  require_head_init(env, config);
  require_js_init(env, config);
  rich_text_init(env, config);
  rss_listing_init(env, config);
  section_header_init(env, config);
  simple_menu_init(env, config);
  social_sharing_init(env, config);
  space_init(env, config);
  text_init(env, config);
  textarea_init(env, config);
  video_player_init(env, config);
  widget_attribute_init(env, config);
  widget_block_init(env, config);
  widget_container_init(env, config);
};