

import blog_all_posts_url_init from './blog_all_posts_url.js';
import blog_author_url_init from './blog_author_url.js';
import blog_authors_init from './blog_authors.js';
import blog_by_id_init from './blog_by_id.js';
import blog_page_link_init from './blog_page_link.js';
import blog_popular_posts_init from './blog_popular_posts.js';
import blog_post_archive_url_init from './blog_post_archive_url.js';
import blog_recent_author_posts_init from './blog_recent_author_posts.js';
import blog_recent_posts_init from './blog_recent_posts.js';
import blog_recent_tag_posts_init from './blog_recent_tag_posts.js';
import blog_recent_topic_posts_init from './blog_recent_topic_posts.js';
import blog_tag_url_init from './blog_tag_url.js';
import blog_tags_init from './blog_tags.js';
import blog_total_post_count_init from './blog_total_post_count.js';
import color_variant_init from './color_variant.js';
import content_by_id_init from './content_by_id.js';
import content_by_ids_init from './content_by_ids.js';
import crm_associations_init from './crm_associations.js';
import crm_object_init from './crm_object.js';
import crm_objects_init from './crm_objects.js';
import cta_init from './cta.js';
import datetimeformat_init from './datetimeformat.js';
import file_by_id_init from './file_by_id.js';
import geo_distance_init from './geo_distance.js';
import get_asset_url_init from './get_asset_url.js';
import get_public_template_url_by_id_init from './get_public_template_url_by_id.js';
import get_public_template_url_init from './get_public_template_url.js';
import head_css_init from './head_css.js';
import head_elements_init from './head_elements.js';
import head_js_init from './head_js.js';
import hubdb_table_column_init from './hubdb_table_column.js';
import hubdb_table_row_init from './hubdb_table_row.js';
import hubdb_table_rows_init from './hubdb_table_rows.js';
import hubdb_table_init from './hubdb_table.js';
import i18n_getlanguage_init from './i18n_getlanguage.js';
import i18n_getmessage_init from './i18n_getmessage.js';
import include_css_init from './include_css.js';
import include_javascript_init from './include_javascript.js';
import locale_name_init from './locale_name.js';
import menu_init from './menu.js';
import module_asset_url_init from './module_asset_url.js';
import page_by_id_init from './page_by_id.js';
import personalization_token_init from './personalization_token.js';
import postal_location_init from './postal_location.js';
import range_init from './range.js';
import require_css_init from './require_css.js';
import require_js_init from './require_js.js';
import resize_image_url_init from './resize_image_url.js';
import script_embed_init from './script_embed.js';
import set_response_code_init from './set_response_code.js';
import strtotime_init from './strtotime.js';
import super_init from './super.js';
import to_local_time_init from './to_local_time.js';
import today_init from './today.js';
import topic_cluster_by_content_id_init from './topic_cluster_by_content_id.js';
import truncate_init from './truncate.js';
import type_init from './type.js';
import unixtimestamp_init from './unixtimestamp.js';
import video_metadata_by_player_id_init from './video_metadata_by_player_id.js';
import video_thumbnail_init from './video_thumbnail.js';

export default function configure(env, config) {
  
  blog_all_posts_url_init(env, config);
  blog_author_url_init(env, config);
  blog_authors_init(env, config);
  blog_by_id_init(env, config);
  blog_page_link_init(env, config);
  blog_popular_posts_init(env, config);
  blog_post_archive_url_init(env, config);
  blog_recent_author_posts_init(env, config);
  blog_recent_posts_init(env, config);
  blog_recent_tag_posts_init(env, config);
  blog_recent_topic_posts_init(env, config);
  blog_tag_url_init(env, config);
  blog_tags_init(env, config);
  blog_total_post_count_init(env, config);
  color_variant_init(env, config);
  content_by_id_init(env, config);
  content_by_ids_init(env, config);
  crm_associations_init(env, config);
  crm_object_init(env, config);
  crm_objects_init(env, config);
  cta_init(env, config);
  datetimeformat_init(env, config);
  file_by_id_init(env, config);
  geo_distance_init(env, config);
  get_asset_url_init(env, config);
  get_public_template_url_by_id_init(env, config);
  get_public_template_url_init(env, config);
  head_css_init(env, config);
  head_elements_init(env, config);
  head_js_init(env, config);
  hubdb_table_column_init(env, config);
  hubdb_table_row_init(env, config);
  hubdb_table_rows_init(env, config);
  hubdb_table_init(env, config);
  i18n_getlanguage_init(env, config);
  i18n_getmessage_init(env, config);
  include_css_init(env, config);
  include_javascript_init(env, config);
  locale_name_init(env, config);
  menu_init(env, config);
  module_asset_url_init(env, config);
  page_by_id_init(env, config);
  personalization_token_init(env, config);
  postal_location_init(env, config);
  range_init(env, config);
  require_css_init(env, config);
  require_js_init(env, config);
  resize_image_url_init(env, config);
  script_embed_init(env, config);
  set_response_code_init(env, config);
  strtotime_init(env, config);
  super_init(env, config);
  to_local_time_init(env, config);
  today_init(env, config);
  topic_cluster_by_content_id_init(env, config);
  truncate_init(env, config);
  type_init(env, config);
  unixtimestamp_init(env, config);
  video_metadata_by_player_id_init(env, config);
  video_thumbnail_init(env, config);
};