

import blog_all_posts_url_fn from './blog_all_posts_url.js';
import blog_author_url_fn from './blog_author_url.js';
import blog_authors_fn from './blog_authors.js';
import blog_by_id_fn from './blog_by_id.js';
import blog_page_link_fn from './blog_page_link.js';
import blog_popular_posts_fn from './blog_popular_posts.js';
import blog_post_archive_url_fn from './blog_post_archive_url.js';
import blog_post_by_id_fn from './blog_post_by_id.js';
import blog_recent_author_posts_fn from './blog_recent_author_posts.js';
import blog_recent_posts_fn from './blog_recent_posts.js';
import blog_recent_tag_posts_fn from './blog_recent_tag_posts.js';
import blog_recent_topic_posts_fn from './blog_recent_topic_posts.js';
import blog_tag_url_fn from './blog_tag_url.js';
import blog_tags_fn from './blog_tags.js';
import blog_topics_fn from './blog_topics.js';
import blog_total_post_count_fn from './blog_total_post_count.js';
import color_variant_fn from './color_variant.js';
import content_by_id_fn from './content_by_id.js';
import content_by_ids_fn from './content_by_ids.js';
import crm_associations_fn from './crm_associations.js';
import crm_object_fn from './crm_object.js';
import crm_objects_fn from './crm_objects.js';
import crm_property_definition_fn from './crm_property_definition.js';
import crm_property_definitions_fn from './crm_property_definitions.js';
import cta_fn from './cta.js';
import datetimeformat_fn from './datetimeformat.js';
import facebook_messenger_link_fn from './facebook_messenger_link.js';
import file_by_id_fn from './file_by_id.js';
import follow_me_links_fn from './follow_me_links.js';
import footer_js_fn from './footer_js.js';
import geo_distance_fn from './geo_distance.js';
import get_asset_url_fn from './get_asset_url.js';
import get_public_template_url_by_id_fn from './get_public_template_url_by_id.js';
import get_public_template_url_fn from './get_public_template_url.js';
import head_css_fn from './head_css.js';
import head_elements_fn from './head_elements.js';
import head_js_fn from './head_js.js';
import hubdb_table_column_fn from './hubdb_table_column.js';
import hubdb_table_row_fn from './hubdb_table_row.js';
import hubdb_table_rows_fn from './hubdb_table_rows.js';
import hubdb_table_fn from './hubdb_table.js';
import i18n_getlanguage_fn from './i18n_getlanguage.js';
import i18n_getmessage_fn from './i18n_getmessage.js';
import include_css_fn from './include_css.js';
import include_javascript_fn from './include_javascript.js';
import locale_name_fn from './locale_name.js';
import menu_fn from './menu.js';
import module_asset_url_fn from './module_asset_url.js';
import oembed_fn from './oembed.js';
import page_by_id_fn from './page_by_id.js';
import personalization_token_fn from './personalization_token.js';
import postal_location_fn from './postal_location.js';
import range_fn from './range.js';
import require_css_fn from './require_css.js';
import require_js_fn from './require_js.js';
import resize_image_url_fn from './resize_image_url.js';
import script_embed_fn from './script_embed.js';
import set_response_code_fn from './set_response_code.js';
import strtotime_fn from './strtotime.js';
import super_fn from './super.js';
import to_local_time_fn from './to_local_time.js';
import today_fn from './today.js';
import topic_cluster_by_content_id_fn from './topic_cluster_by_content_id.js';
import truncate_fn from './truncate.js';
import type_fn from './type.js';
import unixtimestamp_fn from './unixtimestamp.js';
import video_metadata_by_player_id_fn from './video_metadata_by_player_id.js';
import video_thumbnail_fn from './video_thumbnail.js';

export default function configure(env, config) {
  
  blog_all_posts_url_fn.register(env, config);
  blog_author_url_fn.register(env, config);
  blog_authors_fn.register(env, config);
  blog_by_id_fn.register(env, config);
  blog_page_link_fn.register(env, config);
  blog_popular_posts_fn.register(env, config);
  blog_post_archive_url_fn.register(env, config);
  blog_post_by_id_fn.register(env, config);
  blog_recent_author_posts_fn.register(env, config);
  blog_recent_posts_fn.register(env, config);
  blog_recent_tag_posts_fn.register(env, config);
  blog_recent_topic_posts_fn.register(env, config);
  blog_tag_url_fn.register(env, config);
  blog_tags_fn.register(env, config);
  blog_topics_fn.register(env, config);
  blog_total_post_count_fn.register(env, config);
  color_variant_fn.register(env, config);
  content_by_id_fn.register(env, config);
  content_by_ids_fn.register(env, config);
  crm_associations_fn.register(env, config);
  crm_object_fn.register(env, config);
  crm_objects_fn.register(env, config);
  crm_property_definition_fn.register(env, config);
  crm_property_definitions_fn.register(env, config);
  cta_fn.register(env, config);
  datetimeformat_fn.register(env, config);
  facebook_messenger_link_fn.register(env, config);
  file_by_id_fn.register(env, config);
  follow_me_links_fn.register(env, config);
  footer_js_fn.register(env, config);
  geo_distance_fn.register(env, config);
  get_asset_url_fn.register(env, config);
  get_public_template_url_by_id_fn.register(env, config);
  get_public_template_url_fn.register(env, config);
  head_css_fn.register(env, config);
  head_elements_fn.register(env, config);
  head_js_fn.register(env, config);
  hubdb_table_column_fn.register(env, config);
  hubdb_table_row_fn.register(env, config);
  hubdb_table_rows_fn.register(env, config);
  hubdb_table_fn.register(env, config);
  i18n_getlanguage_fn.register(env, config);
  i18n_getmessage_fn.register(env, config);
  include_css_fn.register(env, config);
  include_javascript_fn.register(env, config);
  locale_name_fn.register(env, config);
  menu_fn.register(env, config);
  module_asset_url_fn.register(env, config);
  oembed_fn.register(env, config);
  page_by_id_fn.register(env, config);
  personalization_token_fn.register(env, config);
  postal_location_fn.register(env, config);
  range_fn.register(env, config);
  require_css_fn.register(env, config);
  require_js_fn.register(env, config);
  resize_image_url_fn.register(env, config);
  script_embed_fn.register(env, config);
  set_response_code_fn.register(env, config);
  strtotime_fn.register(env, config);
  super_fn.register(env, config);
  to_local_time_fn.register(env, config);
  today_fn.register(env, config);
  topic_cluster_by_content_id_fn.register(env, config);
  truncate_fn.register(env, config);
  type_fn.register(env, config);
  unixtimestamp_fn.register(env, config);
  video_metadata_by_player_id_fn.register(env, config);
  video_thumbnail_fn.register(env, config);
};