import add_init from './add.js';
import attr_init from './attr.js';
import between_times_init from './between_times.js';
import bool_init from './bool.js';
import convert_rgb_init from './convert_rgb.js';
import count_init from './count.js';
import cut_init from './cut.js';
import datetimeformat_init from './datetimeformat.js';
import default_init from './default.js';
import difference_init from './difference.js';
import divide_init from './divide.js';
import divisible_init from './divisible.js';
import escape_jinjava_init from './escape_jinjava.js';
import escapejs_init from './escapejs.js';
import escapejson_init from './escapejson.js';
import filesizeformat_init from './filesizeformat.js';
import format_currency_init from './format_currency.js';
import format_init from './format.js';
import fromjson_init from './fromjson.js';
import geo_distance_init from './geo_distance.js';
import int_init from './int.js';
import intersect_init from './intersect.js';
import ipaddr_init from './ipaddr.js';
import length_init from './length.js';
import log_init from './log.js';
import map_init from './map.js';
import md5_init from './md5.js';
import minus_time_init from './minus_time.js';
import multiply_init from './multiply.js';
import plus_time_init from './plus_time.js';
import pprint_init from './pprint.js';
import regex_replace_init from './regex_replace.js';
import reject_init from './reject.js';
import render_init from './render.js';
import root_init from './root.js';
import select_init from './select.js';
import shuffle_init from './shuffle.js';
import sort_init from './sort.js';
import split_init from './split.js';
import strtotime_init from './strtotime.js';
import symmetric_difference_init from './symmetric_difference.js';
import tojson_init from './tojson.js';
import truncatehtml_init from './truncatehtml.js';
import union_init from './union.js';
import unique_init from './unique.js';
import unixtimestamp_init from './unixtimestamp.js';
import wordwrap_init from './wordwrap.js';
import xmlattr_init from './xmlattr.js';
import float_init from './float.js';
import upper_init from './upper.js';
import lower_init from './lower.js';
import random_init from './random.js';
import groupby_init from './groupby.js';

export default function configure(env, config) {
  
  add_init(env, config);
  attr_init(env, config);
  between_times_init(env, config);
  bool_init(env, config);
  convert_rgb_init(env, config);
  count_init(env, config);
  cut_init(env, config);
  datetimeformat_init(env, config);
  default_init(env, config);
  difference_init(env, config);
  divide_init(env, config);
  divisible_init(env, config);
  escape_jinjava_init(env, config);
  escapejs_init(env, config);
  escapejson_init(env, config);
  filesizeformat_init(env, config);
  format_currency_init(env, config);
  format_init(env, config);
  fromjson_init(env, config);
  geo_distance_init(env, config);
  int_init(env, config);
  intersect_init(env, config);
  ipaddr_init(env, config);
  length_init(env, config);
  log_init(env, config);
  map_init(env, config);
  md5_init(env, config);
  minus_time_init(env, config);
  multiply_init(env, config);
  plus_time_init(env, config);
  pprint_init(env, config);
  regex_replace_init(env, config);
  reject_init(env, config);
  render_init(env, config);
  root_init(env, config);
  select_init(env, config);
  shuffle_init(env, config);
  sort_init(env, config);
  split_init(env, config);
  strtotime_init(env, config);
  symmetric_difference_init(env, config);
  tojson_init(env, config);
  truncatehtml_init(env, config);
  union_init(env, config);
  unique_init(env, config);
  unixtimestamp_init(env, config);
  wordwrap_init(env, config);
  xmlattr_init(env, config);
  float_init(env, config);
  upper_init(env, config);
  lower_init(env, config);
  random_init(env, config);
  groupby_init(env, config);
};