

import add_filter from './add.js';
import attr_filter from './attr.js';
import between_times_filter from './between_times.js';
import bool_filter from './bool.js';
import convert_rgb_filter from './convert_rgb.js';
import count_filter from './count.js';
import cut_filter from './cut.js';
import d_filter from './d.js';
import date_filter from './date.js';
import datetimeformat_filter from './datetimeformat.js';
import default_filter from './default.js';
import difference_filter from './difference.js';
import divide_filter from './divide.js';
import divisible_filter from './divisible.js';
import e_filter from './e.js';
import escape_jinjava_filter from './escape_jinjava.js';
import escapejs_filter from './escapejs.js';
import escapejson_filter from './escapejson.js';
import filesizeformat_filter from './filesizeformat.js';
import format_currency_filter from './format_currency.js';
import format_filter from './format.js';
import fromjson_filter from './fromjson.js';
import fromyaml_filter from './fromyaml.js';
import geo_distance_filter from './geo_distance.js';
import int_filter from './int.js';
import intersect_filter from './intersect.js';
import ipaddr_filter from './ipaddr.js';
import ipv4_filter from './ipv4.js';
import ipv6_filter from './ipv6.js';
import length_filter from './length.js';
import log_filter from './log.js';
import map_filter from './map.js';
import md5_filter from './md5.js';
import minus_time_filter from './minus_time.js';
import multiply_filter from './multiply.js';
import plus_time_filter from './plus_time.js';
import pprint_filter from './pprint.js';
import regex_replace_filter from './regex_replace.js';
import reject_filter from './reject.js';
import render_filter from './render.js';
import root_filter from './root.js';
import select_filter from './select.js';
import shuffle_filter from './shuffle.js';
import sort_filter from './sort.js';
import split_filter from './split.js';
import strtotime_filter from './strtotime.js';
import symmetric_difference_filter from './symmetric_difference.js';
import tojson_filter from './tojson.js';
import toyaml_filter from './toyaml.js';
import truncatehtml_filter from './truncatehtml.js';
import union_filter from './union.js';
import unique_filter from './unique.js';
import unixtimestamp_filter from './unixtimestamp.js';
import wordwrap_filter from './wordwrap.js';
import xmlattr_filter from './xmlattr.js';

export default function configure(env, config) {
  
  add_filter.register(env, config);
  attr_filter.register(env, config);
  between_times_filter.register(env, config);
  bool_filter.register(env, config);
  convert_rgb_filter.register(env, config);
  count_filter.register(env, config);
  cut_filter.register(env, config);
  d_filter.register(env, config);
  date_filter.register(env, config);
  datetimeformat_filter.register(env, config);
  default_filter.register(env, config);
  difference_filter.register(env, config);
  divide_filter.register(env, config);
  divisible_filter.register(env, config);
  e_filter.register(env, config);
  escape_jinjava_filter.register(env, config);
  escapejs_filter.register(env, config);
  escapejson_filter.register(env, config);
  filesizeformat_filter.register(env, config);
  format_currency_filter.register(env, config);
  format_filter.register(env, config);
  fromjson_filter.register(env, config);
  fromyaml_filter.register(env, config);
  geo_distance_filter.register(env, config);
  int_filter.register(env, config);
  intersect_filter.register(env, config);
  ipaddr_filter.register(env, config);
  ipv4_filter.register(env, config);
  ipv6_filter.register(env, config);
  length_filter.register(env, config);
  log_filter.register(env, config);
  map_filter.register(env, config);
  md5_filter.register(env, config);
  minus_time_filter.register(env, config);
  multiply_filter.register(env, config);
  plus_time_filter.register(env, config);
  pprint_filter.register(env, config);
  regex_replace_filter.register(env, config);
  reject_filter.register(env, config);
  render_filter.register(env, config);
  root_filter.register(env, config);
  select_filter.register(env, config);
  shuffle_filter.register(env, config);
  sort_filter.register(env, config);
  split_filter.register(env, config);
  strtotime_filter.register(env, config);
  symmetric_difference_filter.register(env, config);
  tojson_filter.register(env, config);
  toyaml_filter.register(env, config);
  truncatehtml_filter.register(env, config);
  union_filter.register(env, config);
  unique_filter.register(env, config);
  unixtimestamp_filter.register(env, config);
  wordwrap_filter.register(env, config);
  xmlattr_filter.register(env, config);
};